### ISSUE TITLE
Read HTML for DH2017

### ISSUE THREAD

**Issue by lehkost** [lehkost/ToolXtractor#2]
Right now, only TEI files are read by ToolXtractor. Make it work for HTML (which is the format provided for DH2017).
For title extraction, maybe use the first non-empty element after ```<body>```.
Data in question is here: https://github.com/ADHO/dh2017/tree/master/html

**Comment by yoannspace** [comment]
Those HTML files are sometimes very badly encoded...
For example:
[Fatal Error] :41:253: The element type "sub" must be terminated by the matching end-tag "</sub>".
Error parsing ToolXtractor/data/html/2017/488.html
If you look at https://github.com/lehkost/ToolXtractor/blob/master/data/html/2017/488.html#L41 you will see that the element `<sub>` is not closed...
This happens for a lot of HTML files...

**Comment by lehkost** [comment]
Articles for DH2017 have also been added in TXT format (dumps created using ```w3m``` which can also render non-well-formed documents). Commit: https://github.com/lehkost/ToolXtractor/commit/197767e74ffa1bfbf1526d40a8f8976f510a3b0b

**Comment by yoannspace** [comment]
This has been fixed in https://github.com/lehkost/ToolXtractor/commit/47b8d11cd787c12ddf498a155582f0a519b27b43
